import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

import pytest

from src.contracts import CandidateProfile
from src.dsl import render_html, save_html, to_dsl_text, validate
from src.vocabulary import Profile

ROOT = Path(__file__).resolve().parent.parent
VALID = sorted((ROOT / "examples" / "dsl" / "valid").glob("*.rl"))
VOID = {"meta", "br", "hr", "img", "input", "link"}


class Collector(HTMLParser):
    """Collects tags and text, and checks that tags are balanced."""

    def __init__(self):
        super().__init__()
        self.stack: list[str] = []
        self.tags: list[tuple[str, dict]] = []
        self.text: list[str] = []
        self.balanced = True

    def handle_starttag(self, tag, attrs):
        self.tags.append((tag, dict(attrs)))
        if tag not in VOID:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if not self.stack or self.stack.pop() != tag:
            self.balanced = False

    def handle_data(self, data):
        self.text.append(data)


def parse_html(html: str) -> Collector:
    collector = Collector()
    collector.feed(html)
    collector.close()
    return collector


def classes(page: Collector, name: str) -> list[str]:
    return [t for t, a in page.tags if name in (a.get("class") or "").split()]


def candidate(**changes) -> CandidateProfile:
    base = dict(
        name="Wednesday Addams",
        emails=[],
        phones=[],
        experience_years=3,
        education=[],
        skills=["JAVASCRIPT", "REACT", "NODE_JS", "POSTGRESQL", "GIT"],
        classifications={
            Profile.FULL_STACK_DEVELOPER: True,
            Profile.MACHINE_LEARNING_ENGINEER: False,
            Profile.BACKEND_DEVELOPER: False,
            Profile.DATA_SCIENTIST: False,
        },
    )
    base.update(changes)
    return CandidateProfile(**base)


def render(**changes) -> str:
    return render_html(validate(to_dsl_text(candidate(**changes))))


# --- the example profiles ---------------------------------------------------------


@pytest.mark.parametrize("path", VALID, ids=[p.stem for p in VALID])
def test_every_valid_example_renders_a_well_formed_page(path):
    html = render_html(validate(path.read_text(encoding="utf-8")))
    page = parse_html(html)
    assert page.balanced and page.stack == []
    assert html.startswith("<!DOCTYPE html>")
    assert '<html lang="en">' in html
    assert '<meta charset="UTF-8">' in html


@pytest.mark.parametrize("path", VALID, ids=[p.stem for p in VALID])
def test_page_shows_one_result_per_profile(path):
    page = parse_html(render_html(validate(path.read_text(encoding="utf-8"))))
    assert len(classes(page, "result")) == len(Profile)


def test_page_has_the_sections_of_the_assignment_example():
    text = " ".join(parse_html(render()).text)
    assert "Wednesday Addams" in text
    assert "Candidate profile generated by ResumeLens" in text
    assert "Normalized Technical Skills" in text
    assert "Qualification Evaluation" in text
    assert "Full Stack Developer" in text
    assert "ACCEPTED" in text


def test_skills_are_listed_in_order():
    text = [t.strip() for t in parse_html(render()).text if t.strip()]
    start = text.index("JAVASCRIPT")
    assert text[start : start + 5] == ["JAVASCRIPT", "REACT", "NODE_JS", "POSTGRESQL", "GIT"]


def test_each_skill_shows_its_category():
    page = parse_html(render())
    titles = [a["title"] for t, a in page.tags if "skill" in (a.get("class") or "").split()]
    assert titles == ["Language", "Frontend", "Backend", "Database", "Version Control"]


def test_accepted_and_rejected_profiles_are_marked():
    page = parse_html(render())
    assert len(classes(page, "accepted")) == 1
    assert len(classes(page, "rejected")) == 3
    text = " ".join(page.text)
    assert "Accepted profiles: Full Stack Developer" in text
    assert text.count("REJECTED") == 3


def test_summary_when_nothing_is_accepted():
    html = render(classifications={p: False for p in Profile})
    assert "No qualification pattern was satisfied." in html
    assert "Accepted profiles" not in html


def test_several_accepted_profiles_are_listed():
    html = render(
        classifications={
            Profile.FULL_STACK_DEVELOPER: True,
            Profile.MACHINE_LEARNING_ENGINEER: True,
        }
    )
    assert "Accepted profiles: Full Stack Developer, Machine Learning Engineer" in html


# --- optional sections ---------------------------------------------------------------


def test_empty_sections_are_not_rendered():
    html = render(experience_years=None, experience=[], skills=[])
    assert "<h2>Contact</h2>" not in html
    assert "<h2>Experience</h2>" not in html
    assert "<h2>Education</h2>" not in html
    assert "No technical skills were recognized" in html


def test_full_profile_has_every_section():
    html = render(
        emails=["wa@example.com"],
        phones=["+57 300 123 4567"],
        links=["github.com/wa"],
        education=["Universidad Icesi"],
        experience=["Backend Developer at Acme (2020 - 2023)"],
    )
    for heading in ("Contact", "Experience", "Education", "Normalized Technical Skills"):
        assert f"<h2>{heading}</h2>" in html
    assert "Backend Developer at Acme (2020 - 2023)" in html
    assert "Universidad Icesi" in html


@pytest.mark.parametrize("years, expected", [(1, "1 year"), (0, "0 years"), (3, "3 years")])
def test_years_are_pluralized(years, expected):
    assert f"<strong>{expected}</strong>" in render(experience_years=years)


def test_years_are_not_shown_when_unknown():
    html = render(experience_years=None, experience=["Intern at Acme"])
    assert "of experience" not in html
    assert "Intern at Acme" in html


# --- contact links ---------------------------------------------------------------------


def test_contact_values_become_links():
    html = render(
        emails=["wa@example.com"],
        phones=["+57 300 123 4567"],
        links=["github.com/wa", "https://wa.dev/x", "www.wa.dev"],
    )
    assert 'href="mailto:wa@example.com"' in html
    assert 'href="tel:+573001234567"' in html
    assert 'href="https://github.com/wa"' in html
    assert 'href="https://wa.dev/x"' in html
    assert 'href="https://www.wa.dev"' in html


def test_dangerous_links_are_shown_as_text_only():
    html = render(links=["javascript:alert(1)", "data:text/html,hi"])
    assert "javascript:alert(1)" in html
    assert 'href="javascript' not in html
    assert 'href="data' not in html


# --- escaping --------------------------------------------------------------------------


def test_text_from_the_resume_is_escaped():
    html = render(
        name="Ana <script>alert(1)</script> & Co",
        experience=["<img src=x onerror=alert(1)>"],
        education=["R&D <b>Lab</b>"],
    )
    assert "<script>alert" not in html
    assert "<img src=x" not in html
    assert "<b>Lab</b>" not in html
    assert "Ana &lt;script&gt;alert(1)&lt;/script&gt; &amp; Co" in html
    assert "R&amp;D &lt;b&gt;Lab&lt;/b&gt;" in html
    assert parse_html(html).balanced


def test_title_is_escaped_too():
    html = render(name="</title><script>x</script>")
    assert "<title>&lt;/title&gt;&lt;script&gt;x&lt;/script&gt; - ResumeLens</title>" in html


def test_page_is_self_contained():
    html = render(links=["https://wa.dev"])
    tags = {tag for tag, _ in parse_html(html).tags}
    assert not tags & {"script", "img", "iframe", "object", "link"}
    assert "@import" not in html and "src=" not in html


def test_accents_survive():
    assert "María José Pérez-Núñez" in render(name="María José Pérez-Núñez")


def test_rendering_is_deterministic():
    assert render() == render()


# --- saving and command line ----------------------------------------------------------


def test_save_html_writes_utf8_and_creates_folders(tmp_path):
    html = render(name="Sofía Núñez")
    path = save_html(html, tmp_path / "out" / "page.html")
    assert path.read_text(encoding="utf-8") == html


def run_cli(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "src.dsl", *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )


def test_command_line_renders_a_valid_profile(tmp_path):
    out = tmp_path / "wa.html"
    result = run_cli(str(ROOT / "examples/dsl/valid/wednesday_addams.rl"), str(out))
    assert result.returncode == 0
    assert "Wednesday Addams" in out.read_text(encoding="utf-8")


def test_command_line_rejects_an_invalid_profile(tmp_path):
    out = tmp_path / "bad.html"
    result = run_cli(str(ROOT / "examples/dsl/invalid/semantic_unknown_skill.rl"), str(out))
    assert result.returncode == 1
    assert "S1" in result.stderr
    assert not out.exists()


def test_command_line_without_arguments_prints_usage():
    result = run_cli()
    assert result.returncode == 2
    assert "usage" in result.stderr


def test_committed_samples_are_up_to_date():
    samples = ROOT / "docs" / "samples"
    for path in VALID:
        expected = render_html(validate(path.read_text(encoding="utf-8")))
        assert (samples / f"{path.stem}.html").read_text(encoding="utf-8") == expected, path.stem
