// SEMANTIC S3: a profile appears twice
candidate "Ana" { skills { GIT } results { FULL_STACK_DEVELOPER: ACCEPTED FULL_STACK_DEVELOPER: REJECTED MACHINE_LEARNING_ENGINEER: REJECTED BACKEND_DEVELOPER: REJECTED DATA_SCIENTIST: REJECTED } }
