// SEMANTIC S2: GIT appears twice
candidate "Ana" { skills { GIT, GIT } results { FULL_STACK_DEVELOPER: REJECTED MACHINE_LEARNING_ENGINEER: REJECTED BACKEND_DEVELOPER: REJECTED DATA_SCIENTIST: REJECTED } }
