// SEMANTIC S1: COBOL is a valid token but not in the vocabulary
candidate "Ana" { skills { COBOL } results { FULL_STACK_DEVELOPER: REJECTED MACHINE_LEARNING_ENGINEER: REJECTED BACKEND_DEVELOPER: REJECTED DATA_SCIENTIST: REJECTED } }
