// SYNTAX: results cannot come before skills
candidate "Ana" { results { FULL_STACK_DEVELOPER: REJECTED MACHINE_LEARNING_ENGINEER: REJECTED BACKEND_DEVELOPER: REJECTED DATA_SCIENTIST: REJECTED } skills { GIT } }
